#ifndef DIMSERVER
#define DIMSERVER     'S'
#endif
#ifndef DIMCLIENT
#define DIMCLIENT     'C'
#endif
#ifndef DIMSERVICE
#define DIMSERVICE    'S'
#endif
#ifndef DIMCOMMAND
#define DIMCOMMAND    'C'
#endif
#ifndef DIMTIERTYPE
#define DIMTIERTYPE   'T'
#endif
#ifndef DIMSERVERSNAMEPREFIX
#define DIMSERVERSNAMEPREFIX 'N'
#endif
#ifndef DIMDNSADDRESS
#define DIMDNSADDRESS 'A'
#endif
#ifndef DIMDNSPORT
#define DIMDNSPORT    'P'
#endif
#ifndef DIMEXTENSIONS
#define DIMEXTENSIONS 'X'
#endif
#ifndef DIMEXTENSIONSGETSUFFIX
#define DIMEXTENSIONSGETSUFFIX      'g'
#endif
#ifndef DIMEXTENSIONSPUTSUFFIX
#define DIMEXTENSIONSPUTSUFFIX      'p'
#endif
#ifndef DIMEXTENSIONSCREATE      
#define DIMEXTENSIONSCREATE         'c'
#endif
#ifndef DIMEXTENSIONSTRINGTRANSPORT
#define DIMEXTENSIONSTRINGTRANSPORT 's'
#endif
#ifndef DIMEXTENSIONSCREATEBOTH      
#define DIMEXTENSIONSCREATEBOTH            'b'
#endif
#ifndef DIMEXTENSIONSTRINGTRANSPORTSERVICE
#define DIMEXTENSIONSTRINGTRANSPORTSERVICE 's'
#endif
#ifndef DIMEXTENSIONSTRINGTRANSPORTCOMMAND
#define DIMEXTENSIONSTRINGTRANSPORTCOMMAND 'c'
#endif
#ifndef DIMEXTENSIONSTRINGTRANSPORTBOTH
#define DIMEXTENSIONSTRINGTRANSPORTBOTH    'b'
#endif 

#ifndef DIMFORMAT
#define DIMFORMAT              'f'
#endif
#ifndef DIMSERVICESCANINTERVAL
#define DIMSERVICESCANINTERVAL 'i'
#endif
#ifndef DIMSERVICESCANTYPE
#define DIMSERVICESCANTYPE     's'
#endif
#ifndef DIMSCANTYPETIMED
#define DIMSCANTYPETIMED       'T'
#endif
#ifndef DIMSCANTYPEMONITORED
#define DIMSCANTYPEMONITORED   'M'
#endif

#ifndef DIMDEFAULTGETSUFFIX
#define DIMDEFAULTGETSUFFIX "_CAGET"
#endif
#ifndef DIMDEFAULTPUTSUFFIX
#define DIMDEFAULTPUTSUFFIX "_CAPUT"
#endif
#ifndef DIMSERVERNODEPREFIX
#define DIMSERVERNODEPREFIX "EPICS_DIM"
#endif
#ifndef DIMSERVERPIDPREFIX
#define DIMSERVERPIDPREFIX  "PID-"
#endif
#ifndef DIMSERVERNODEPIDSEPARATOR
#define DIMSERVERNODEPIDSEPARATOR ":"
#endif
#ifndef DIMSERVERATNODESEPARATOR
#define DIMSERVERATNODESEPARATOR "@"
#endif
#ifndef DIMSERVERNODEPORTSEPARATOR
#define DIMSERVERNODEPORTSEPARATOR ":"
#endif

#ifndef DIMSERVICESPREFIXSEPARATOR
#define DIMSERVICESPREFIXSEPARATOR "/"
#endif

#ifndef DIM_SPACE_TOKEN
#define DIM_SPACE_TOKEN " "
#endif

#ifndef DIM_PRIMARY_TOKEN
#define DIM_PRIMARY_TOKEN "@"
#endif

#ifndef DIM_SECONDARY_TOKEN
#define DIM_SECONDARY_TOKEN "="
#endif

#ifndef DIM_THIRD_TOKEN
#define DIM_THIRD_TOKEN "'"
#endif

#ifndef DIM_FOURTH_TOKEN
#define DIM_FOURTH_TOKEN ";"
#endif

#ifndef DIM_FIFTH_TOKEN
#define DIM_FIFTH_TOKEN ":"
#endif

#ifndef DIM TOKEN_PROTECTION
#define DIM_TOKEN_PROTECTION '^'
#endif

#ifndef DIMAIAODEFAULTDATATYPE
#define DIMAIAODEFAULTDATATYPE "D:1"
#endif

#ifndef DIMSTRINGDEFAULTDATATYPE
#define DIMSTRINGDEFAULTDATATYPE "C:40"
#endif
